githubUrl: https://api.github.com
spring:
    datasource:
        password: pa$$word
        url: jdbc:h2:file:~/demodb
        username: tom
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
    profiles:
        active: dev
